### ISSUE TITLE
Annoying "Error while clearing errors: No errors matched the request."

### ISSUE THREAD

**Issue by barsnick** [EVerest/everest-framework#156]
Hi,
when launching any SIL, and also resetting any charging session, I get this burst of errors:
```
[ERRO] manager            void Everest::error::ErrorCommBridge::handle_request_clear_error(const json&) :: Error while clearing errors: No errors matched the request.
[INFO] connector_1:EvseMa  :: All errors cleared
[ERRO] manager            void Everest::error::ErrorCommBridge::handle_request_clear_error(const json&) :: Error while clearing errors: No errors matched the request.
[INFO] connector_1:EvseMa  :: All errors cleared
[ERRO] manager            void Everest::error::ErrorCommBridge::handle_request_clear_error(const json&) :: Error while clearing errors: No errors matched the request.
[INFO] connector_1:EvseMa  :: All errors cleared
```

This behavior was introduced in commit 21b5371ec38158ddfcbe9eea0f92a18154ca3c76.

I would change the implementation, but don't quite understand what the intent of the error message is:

- Warn that the filter may be wrong, because it doesn't match anything.
- Warn that trying to clear didn't do anything.

Either way, I think it should rather be a warning. And probably - depending on intent - remain silent if there were no initial errors anyway.

<details>
  <summary>By the way, here are the detailed session events EvseManager is reporting:</summary>

```json
{
    "error": {
        "error_code": "MREC4OverCurrentFailure",
        "error_description": "",
        "error_severity": "High"
    },
    "event": "PermanentFaultCleared",
    "uuid": ""
}
```

```json
{
    "error": {
        "error_code": "VendorWarning",
        "error_description": "",
        "error_severity": "High"
    },
    "event": "ErrorCleared",
    "uuid": ""
}
```

```json
{
    "error": {
        "error_code": "PowermeterTransactionStartFailed",
        "error_description": "",
        "error_severity": "High"
    },
    "event": "PermanentFaultCleared",
    "uuid": ""
}
```

Each followed up by
```json
{
    "event": "AllErrorsCleared",
    "uuid": ""
}
```
</details>

**Comment by krealyt** [comment]
I will close this issue because I understand that this PR has solved that:
https://github.com/EVerest/everest-core/pull/590

@barsnick Hope that is correct. If not, of course do the reopen thing. :)
